-*- eval: (add-hook 'after-save-hook #'org-babel-tangle nil t)-*-
#+title: Emacs configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :results output silent

* Setup

This is my personal Emacs configuration, tested with Emacs 31.1. Some of its features will not work on earlier Emacs versions.

This configuration is designed to mostly bootstrap itself, but some dependencies need to be manually installed.

Here I use Homebrew to install dependencies because I mostly use MacOS.

Core dependencies:
- ~enchant~ and ~pkgconf~, for spell checking
- ~coreutils~, for the ~gls~ CLI command, which is an alternative to ~ls~ that can be used by dired
- ~cmake~ and ~libtool~, to compile dependencies of vterm and Roam
- ~gh~, the GitHub CLI tool, to let me locally list PRs on GH repositories


#+begin_src shell
brew install enchant pkgconf coreutils cmake libtool gh
gh auth login
#+end_src


Language servers for different programming languages; install the relevant subset:
- ~basedpyright~
- ~gopls~
- ~rust-analyzer~
- ~kotlin-language-server~
- ~typescript-language-server~

#+begin_src shell
brew install basedpyright gopls rust-analyzer kotlin-language-server typescript-language-server
#+end_src


Instructions on how to set Caps Lock to act as Control are [[https://support.apple.com/en-gb/guide/mac-help/mchlp1011/mac][here]]. Remember to do this for each machine and keyboard combination.

Run ~M-x nerd-icons-install-fonts~ to download and install icons used by the ~nerd-icons~ package.

If using Org and Org-Roam for task tracking with this configuration, do the following to set up the inbox file:
- ~org-roam-node-find~ "Inbox", to create a node file called ~roam-inbox.org~
- Rename the file to ~Inbox.org~ (without changing its contents) to match the capture templates


~org-roam-node-find~ needs to be run before org capturing, so that the inbox file is given an ID and recognised by Roam.

* Start

Tweak the startup behaviour. Also, define a file with local-only configuration to be loaded after initialising the Emacs session.

#+begin_src emacs-lisp
  ;;; -*- lexical-binding: t -*-

  ;; _____________________________________________________________________________
  ;; Start loading config
  ;; _____________________________________________________________________________

  (toggle-debug-on-error)

  (setq inhibit-startup-message t)

  (switch-to-buffer "*Messages*")
  (message "Started loading config at %s\n" (format-time-string "%T"))

  (defvar nrm/local-config-file "~/local-config.el"
    "File outside of ~/.emacs.d with configuration relevant only to the current machine.")

  ;; Write all customisation information in the local config file
  (setq custom-file nrm/local-config-file)

  (defun nrm/load-local-config ()
    (load-file nrm/local-config-file)
    (message "Loaded local config!\n"))

  (when (file-exists-p nrm/local-config-file)
    (add-hook 'after-init-hook #'nrm/load-local-config))

#+end_src

* Package management

- Set up the MELPA archive.
- Make sure that use-package is installed, so that it can be used to install all the other packages.
- Always ensure packages to avoid confusion over what is or isn't installed.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Package management
  ;; _____________________________________________________________________________

  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)

  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

* Base Emacs

Settings and key bindings that make common actions faster.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Base Emacs
  ;; _____________________________________________________________________________

  (use-package emacs
    :config
    (set-scroll-bar-mode nil)
    (setq-default indent-tabs-mode nil)
    (tool-bar-mode -1)
    (column-number-mode 1)
    (global-display-line-numbers-mode 1)
    (global-visual-line-mode 1)
    (savehist-mode 1) ;; Order minibuffer completions by recency
    (recentf-mode 1)  ;; Keep track of recently opened files
    ;; Delete trailing whitespace by default; disable minor mode when needed
    (define-globalized-minor-mode
      global-delete-trailing-whitespace-mode
      delete-trailing-whitespace-mode
      delete-trailing-whitespace-mode)
    (global-delete-trailing-whitespace-mode 1)
    (which-key-mode 1)
    (add-to-list 'default-frame-alist '(alpha . (95 . 80)))
    ;; MacOS-specific configuration
    (when (memq system-type '(darwin))
      ;; Make the right option key not act as meta, to let me type characters that need the option key
      (setq ns-right-alternate-modifier 'none)
      (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t)))
    :custom
    (use-short-answers t)
    (recenter-positions '(middle 0.1 0.9))    ;; Tweak recentering to be more comfortable
    (ring-bell-function 'ignore)
    (frame-title-format nil)
    ;; Make help windows behave better
    (help-window-select t)
    (help-window-keep-selected t)
    (save-interprogram-paste-before-kill t) ;; Keep clipboard copies from other applications longer
    :bind
    ;; Cycle through buffers easily
    ("s-<left>" . 'previous-buffer)
    ("s-<right>" . 'next-buffer))

#+end_src

* Frames

** Switching and naming frames

I want to use multi-frame workflows in one of two ways.

With few frames, I want to switch between frames quickly with ~other-frame~.

When I am juggling many things, I want to easily name frames, and navigate to frames by name.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Switching and naming frames
  ;; _____________________________________________________________________________

  (defun nrm/other-frame-dwim ()
    (interactive)
    (if (<= (length (visible-frame-list)) 3)
        (call-interactively #'other-frame)
      (call-interactively #'select-frame-by-name)))

  ;; After deleting a frame, raise the most recently used frame
  (add-to-list 'after-delete-frame-functions (lambda (_deleted-frame) (raise-frame)))

  (global-set-key (kbd "s-`") #'nrm/other-frame-dwim)
  (global-set-key (kbd "s-~") #'set-frame-name)

#+end_src

** Frame layouts

I often want to switch between a few common frame layouts. For example, a narrow centred frame when I want to focus on a single buffer. Or a wider frame to display two side by side buffers.

Ideally, this should be handled by the system window manager, but the commands I usually use on MacOS don't work on Emacs frames for some reason, and I figured it would be more fun to write some Elisp than to reason with MacOS 🙃 As an added bonus, the code here should behave consistently across different OS/window managers – though keep in mind I only tested it on MacOS.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Frame layouts
  ;; _____________________________________________________________________________

  (defvar nrm/single-frame-width 150
    "The default width for most frames.")

  (add-to-list 'default-frame-alist '(fullscreen . fullheight))
  (add-to-list 'default-frame-alist `(width . ,nrm/single-frame-width))
  (setq frame-resize-pixelwise t)

  (use-package transient)

  (transient-define-prefix nrm/frame-layout-transient nil
    "Transient menu for resizing and moving the selected frame."
    [""
     ["Halves"
      ("l" "Left half" (lambda () (interactive) (set-frame-size-and-position (selected-frame) 0.5 1.0 0.0 0.0)))
      ("r" "Right half" (lambda () (interactive) (set-frame-size-and-position (selected-frame) 0.5 1.0 0.5 0.0)))]
     ["Thirds"
      ("<left>" "Left third" (lambda () (interactive) (set-frame-size-and-position (selected-frame) (/ 1.0 3) 1.0 0.0 0.0)))
      ("<up>" "Middle third" (lambda () (interactive) (set-frame-size-and-position (selected-frame) (/ 1.0 3) 1.0 (/ 1.0 3) 0.0)))
      ("<down>" "Middle 2/3" (lambda () (interactive) (set-frame-size-and-position (selected-frame) (/ 2.0 3) 1.0 (/ 1.0 6) 0.0)))
      ("<right>" "Right third" (lambda () (interactive) (set-frame-size-and-position (selected-frame) (/ 1.0 3) 1.0 (/ 2.0 3) 0.0)))
      ("RET" "Maximise" (lambda () (interactive) (set-frame-size-and-position (selected-frame) 1.0 1.0 0.0 0.0)))]
     ["Misc"
      ("d" "Default width" (lambda () (interactive) (set-frame-size-and-position (selected-frame) nrm/single-frame-width 1.0 nil 0.0)))
      ("m" "Faux maximised" (lambda () (interactive) (set-frame-size-and-position (selected-frame) 1.0 1.0 0.0 0.0)))]
     ])

  (global-set-key (kbd "s-l") #'nrm/frame-layout-transient)
#+end_src

* Appearance

Make Emacs look fabulous :sparkles:

** Themes and fonts

I spent more time than I'd like to admit tinkering with these.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Appearance
  ;; _____________________________________________________________________________

  (use-package ef-themes
    :config
    (load-theme 'ef-duo-dark t))

  (use-package fontaine
    :custom
    (fontaine-presets
     '((regular
        :default-family "Menlo"
        :default-height 135)))
    :config
    (fontaine-set-preset 'regular))
#+end_src

** Icons

Icons that make several modes prettier, but don't change functionality.

#+begin_src emacs-lisp
  (use-package nerd-icons)

  (use-package nerd-icons-dired
    :hook (dired-mode . nerd-icons-dired-mode))

  (use-package nerd-icons-ibuffer
    :hook (ibuffer-mode . nerd-icons-ibuffer-mode))

  (use-package nerd-icons-completion)

  (use-package nerd-icons-corfu)
#+end_src

** Modeline

The Doom modeline displays some useful information without much configuration.

#+begin_src emacs-lisp
  (use-package doom-modeline
    :init (doom-modeline-mode 1)
    :custom
    (doom-modeline-total-line-number t)
    (doom-modeline-buffer-encoding nil))
#+end_src

* Completion

** Completing read framework

A set of complementary packages that provide minibuffer completion. I saw this set referred to as the MOVEC pentagram.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Completion
  ;; _____________________________________________________________________________

  ;; VERTical Interactive COmpletion - update the minibuffer completions while typing
  (use-package vertico
    :config
    (vertico-mode 1)
    :custom
    (vertico-count 20)
    (vertico-cycle t))

  ;; Rich annotations in the minibuffer
  (use-package marginalia
    :config
    (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup)
    (marginalia-mode 1))

  ;; Out of order pattern matching completion
  ;; Style dispatchers note: affix ! to invert match; affix & to match annotation instead of candidate
  (use-package orderless
    :custom
    (completion-styles '(orderless basic)))

  ;; Enhanced versions of builtin search and navigation commands
  (use-package consult
    :custom
    (consult-line-start-from-top t)
    :config
    (defun nrm/consult-grep-dwim ()
      (interactive)
      (if (or (vc-root-dir)
              (derived-mode-p 'magit-mode))
          (consult-git-grep)
        (consult-grep)))
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)
    :bind (;; Prefix mnemonic: "alt search"
           ;; Search over org-agenda headings
           ("M-s M-a" . consult-org-agenda)
           ;; Jump to flymake diagnostics; e, w, n to narrow to errors, warnings, notes
           ("M-s M-d" . consult-flymake)
           ;; Recursive grep
           ("M-s M-g" . nrm/consult-grep-dwim)
           ;; Search for file names recursively
           ("M-s M-f" . consult-find)
           ;; Search through the outline (headings) of the buffer
           ("M-s M-o" . consult-outline)
           ;; Search through the imenu items of the buffer
           ("M-s M-i" . consult-imenu)
           ;; Search the current buffer
           ("C-s" . consult-line)
           ;; Switch to another buffer, bookmark, or recently opened file
           ;; Filters: b buffers; SPC hidden buffers; * modified buffers; f recent files; r registers; m bookmarks
           ("C-x b" . consult-buffer)
           ;; Interactively select item to yank from kill-ring
           ("C-M-y" . consult-yank-from-kill-ring)
           ;; Goto position at line:column
           ("M-g M-g" . consult-goto-line)))

  ;; Actions based on context
  (use-package embark
    :bind
    ("C-." . embark-act)
    ("s-." . embark-dwim)
    (:map minibuffer-local-map
          ;; Retains minibuffer behaviour
          ("C-c C-c" . embark-collect)
          ;; Exports contents to a buffer in an appropriate major mode
          ("C-c C-e" . embark-export)))

  (use-package embark-consult)
#+end_src

** Completion at point

These packages enable auto-completion when writing in a buffer.

My rules for how to try completion are as follows:
- Firstly, try to complete a file name or an emoji
- Secondly, try to complete according to the mode-specific completions
  - For example, programming-language specific completions
- Lastly, fall back to "prose completion"
  - That is, try to complete from words I've written before or from a dictionary


In programming modes, emoji completion is disabled by default to avoid conflicts, for example with ~:keywords~ in ELisp, path separators in Rust, account name separators in Beancount, etc. The interactive functions ~nrm/cape-emoji-add~ and ~nrm/cape-emoji-remove~ can be used to override this behaviour ad hoc.


#+begin_src emacs-lisp

  ;; UI for completion at point; use M-SPC to insert a separator
  (use-package corfu
    :config
    (global-corfu-mode 1)
    (corfu-history-mode 1)
    (corfu-popupinfo-mode 1)
    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter)
    :custom
    (corfu-cycle t)
    (corfu-preview-current nil)
    (corfu-popupinfo-delay (cons 1.0 0.1)))

  ;; Extra capfs
  (use-package cape
    :config
    (setq completion-at-point-functions (list (cape-capf-super #'cape-dabbrev #'cape-dict)))
    (defun nrm/capf-order-hook ()
      "Set completion-at-point-functions locally in my preferred order."
      (add-hook 'completion-at-point-functions 'cape-file -90 t)
      (unless (derived-mode-p 'prog-mode)
        (add-hook 'completion-at-point-functions 'cape-emoji -89 t)))
    (add-hook 'after-change-major-mode-hook 'nrm/capf-order-hook)
    (defun nrm/cape-emoji-add ()
      "Adds cape-emoji to completion-at-point-functions."
      (interactive)
      (add-hook 'completion-at-point-functions 'cape-emoji -89 t))
    (defun nrm/cape-emoji-remove ()
      "Removes cape-emoji from completion-at-point-functions."
      (interactive)
      (remove-hook 'completion-at-point-functions 'cape-emoji t)))
#+end_src

* Built-in mode improvements

** Dired

Toggle dired omit mode with "C-x M-o". This mode hides "uninteresting" files such as backup and dot files. This is better than hiding files through options passed to the ls command because it lets me quickly toggle the mode when I need to look at dot files, for example.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Dired
  ;; _____________________________________________________________________________

  (use-package dired
    ;; dired is not a -package.el package, so don't attempt to install it.
    :ensure nil
    :hook (dired-mode . dired-omit-mode)
    :bind
    (:map dired-mode-map
          ("b" . dired-up-directory))
    :custom
    (insert-directory-program "gls")
    (dired-listing-switches "-lah --group-directories-first")
    (dired-kill-when-opening-new-dired-buffer t))

  (use-package dired-x
    ;; Also not a proper -package.el.
    :ensure nil
    :config
    (setq dired-omit-files (concat dired-omit-files "\\|^\\..+$")))

  (use-package wdired
    :custom
    (wdired-use-dired-vertical-movement t))

  (use-package dired-subtree
    :config
    (advice-add 'dired-subtree-toggle :after (lambda (&rest _) (revert-buffer)))
    :bind
    (:map dired-mode-map
          ("<tab>" . dired-subtree-toggle)))
#+end_src

** IBuffer

- Replace ~list-buffers~ with the more powerful, built-in ~ibuffer~.
- By default, group buffers by project.
- Make it easier to collapse groups.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; IBuffer
  ;; _____________________________________________________________________________

  (use-package ibuffer
    ;; ibuffer is not a -package.el package, so don't attempt to install it.
    :ensure nil
    :custom
    (ibuffer-default-sorting-mode 'filename/process)
    (ibuffer-show-empty-filter-groups nil)
    (ibuffer-saved-filter-groups
     (list (cons "Projects" (nrm/ibuffer-project-filter-groups))))
    :hook
    (ibuffer-mode . (lambda () (ibuffer-switch-to-saved-filter-groups "Projects")))
    :config
    (defun nrm/ibuffer-project-filter-groups ()
      (project--read-project-list)
      (mapcar (lambda (project)
                (let ((root-dir (car project))
                      (name (file-name-nondirectory (directory-file-name (car project)))))
                  ;; Some modes list their default-directory as relative paths, others as absolute paths
                  `(,name (or
                           (directory . ,root-dir)
                           (directory . ,(expand-file-name root-dir))))))
              project--list))
    (defun nrm/ibuffer-toggle-current-group()
      (interactive)
      (ibuffer-forward-filter-group)
      (ibuffer-backward-filter-group)
      (ibuffer-toggle-filter-group))
    :bind
    (("C-x C-b" . ibuffer)
     :map ibuffer-mode-map
     ("<tab>" . nrm/ibuffer-toggle-current-group)))
#+end_src

** Ediff

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Ediff
  ;; _____________________________________________________________________________

  (use-package ediff
    :custom
    (ediff-keep-variants nil)
    (ediff-make-buffers-readonly-at-startup t)
    (ediff-split-window-function 'split-window-horizontally)
    (ediff-window-setup-function 'ediff-setup-windows-plain))
#+end_src

** wgrep

As of Emacs 31, ~grep-edit-mode~ exists. I was considering using that by default, but ~wgrep~ [[https://www.reddit.com/r/emacs/comments/1w0086c/is_wgrep_fully_now_superseded_by_grepeditmode/][still has some advantages]]:
- Multi-line edits
- Only actually writing changes at the end, which is cheaper and makes it easier to abort/rollback unwanted changes.


At least for now, keep wgrep for the few cases when it's needed.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Wgrep
  ;; _____________________________________________________________________________

  (use-package wgrep)
#+end_src

** Fast navigation

Avy lets me quickly move point to an arbitrary place in the visible buffer.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Fast navigation
  ;; _____________________________________________________________________________

  (use-package avy
    :bind
    ("s-f" . avy-goto-char-timer)
    ("M-s M-l" . avy-goto-line))
#+end_src

** ace-window

With this configuration, ~ace-window~ is an upgrade over the default ~other-window~ command. With two windows in a frame, it behaves identically. With more than two windows, it lets me move to the target window quicker, without repeated command calls.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; ace-window
  ;; _____________________________________________________________________________

  (use-package ace-window
    :bind ("C-x o" . ace-window)
    :custom
    (aw-scope 'frame))

#+end_src

* Text

Utilities for writing in natural languages:
- Spell check
- Make buffers easier to read by visually wrapping lines early – without actually changing the contents.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Text
  ;; _____________________________________________________________________________

  (use-package text-mode
    :ensure nil
    :custom
    ;; Recent versions of text-mode automatically add an ispell capf
    ;; This annoys me to no end so I disable it here
    (text-mode-ispell-word-completion nil)
    (sentence-end-double-space nil))

  (use-package jinx
    :hook (text-mode . jinx-mode)
    :custom
    (jinx-languages "en_GB pt_PT")
    :bind (("M-$" . jinx-correct)))

  (use-package visual-fill-column
    :hook (text-mode . visual-fill-column-mode)
    :custom
    (visual-fill-column-width 120)
    (visual-fill-column-center-text nil)
    (visual-fill-column-enable-sensible-window-split t)
    :config
    (advice-add 'text-scale-adjust :after #'visual-fill-column-adjust))

#+end_src

* Magit

** Base

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Magit
  ;; _____________________________________________________________________________

  (use-package magit
    :custom
    (magit-diff-refine-hunk 'all)
    :config
    (let ((margin-format '(t "%Y-%m-%d %H:%M " magit-log-margin-width t 18)))
      (dolist (format-var '(magit-log-margin
                            magit-status-margin
                            magit-refs-margin
                            magit-stashes-margin
                            magit-cherry-margin
                            magit-log-select-margin
                            magit-reflog-margin))
        (set format-var margin-format)))
    :bind ("C-x g" . magit-status))

  (use-package magit-gh)
#+end_src

** Repository list: A project dashboard

The idea here is to create a dashboard with an overview of the status of my git repositories, to check if there are local changes that need to be finished/committed/pushed. I reverse sort by version by default so that the most recent projects appear first.

#+begin_src emacs-lisp
  (use-package magit
    :custom
    (magit-repository-directories
     '(("~/.emacs.d/" . 0)
       ("~/projects/" . 1)))
    (magit-repolist-columns
     `(("Name" 25 ,#'magit-repolist-column-ident)
       ("Status" 8 ,#'magit-repolist-column-flags)
       ("Stashes" 10 ,#'magit-repolist-column-stashes)
       ("Branch" 25 ,#'magit-repolist-column-branch)
       ("Version" 25 ,#'magit-repolist-column-version
        ((:sort magit-repolist-version<)))
       ("Unpulled" 10 ,#'magit-repolist-column-unpulled-from-upstream
        ((:right-align t)
         (:sort <)))
       ("Unpushed" 10 ,#'magit-repolist-column-unpushed-to-upstream
        ((:right-align t)
         (:sort <)))))
    (magit-repolist-sort-key '("Version" . t)))

#+end_src

* Org

How meta!

- Make org files look better.
- Don't ask for permission to run code in org babel.
- ~org-tempo~ enables expanding snippets into structures, such as code blocks for specific languages.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Org
  ;; _____________________________________________________________________________

  (use-package org
    :bind
    ("\C-cl" . org-store-link)
    :hook (org-mode . org-indent-mode)
    :custom
    (org-special-ctrl-a/e t)
    (org-special-ctrl-k t)
    (org-ellipsis " ▾")
    (org-startup-folded 'content)
    ;; Always add blank lines before inserted headings, never before list items
    (org-blank-before-new-entry '((heading . t) (plain-list-item . nil)))
    ;; Allow items to be refiled to the top level in a file, rather than under another headline
    (org-refile-use-outline-path 'file)
    ;; Show full file and headline paths in the refile completion buffer
    (org-outline-path-complete-in-steps nil)
    ;; Refile targets to the top of files and headlines, rather than the end
    (org-reverse-note-order t)
    (org-confirm-babel-evaluate nil)
    (org-babel-load-languages '((emacs-lisp . t) (shell . t)))
    :config
    ;; Load the backend required to transcode org to markdown
    (require 'ox-md)
    ;; Save all org buffers after refiling, to prevent entries being lost if Emacs crashes
    (advice-add 'org-refile :after (lambda (&rest _) (org-save-all-org-buffers))))

  (use-package org-bullets
    :after org
    :hook (org-mode . org-bullets-mode)
    :custom
    (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

  (use-package org-tempo
    :ensure nil
    :config
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("sh" . "src shell")))

#+end_src

* Task tracking

** Workflow

My workflow has changed over the years:
- It was originally based on the methodology from "Getting Things Done", by David Allen.
- I decided to tag tasks after seeing the custom agenda commands in [[https://systemcrafters.net/org-mode-productivity/custom-org-agenda-views/][this post]] from System Crafters.
- I decided to represent tasks that are blocked/waiting using tags instead of todo keywords after reading the comments in [[https://www.reddit.com/r/emacs/comments/twlmxy/open_ended_question_what_are_your_orgtodokeywords/][this Reddit post]].

I organise my tasks as follows:
- I use todo keywords to mark where in the workflow the task is: todo -> in progress -> done/cancelled.
- I tag every task with an effort level and the type of task it is.
  - I also use tags to mark whether a task is blocked on something else I must do first, or waiting on someone else.
- I use the built-in priority system to mark tasks that should be worked on soon, so they are more visible in my agenda views. Most tasks don't have an assigned priority.

  #+begin_src emacs-lisp
    (use-package org
      :bind
      (("s-a" . org-agenda)
       ("s-c" . org-capture)
       :map org-mode-map
       ("C-c d" . nrm/org-done-fun))
      :custom
      (org-todo-keywords '((sequence "TODO(t)" "PROG(p)" "|" "DONE(d)" "CANCELLED(c)")))
      (org-tag-alist
       '((:startgroup)
         ("@low" . ?l) ("@medium" . ?m) ("@high" . ?h)
         (:endgroup)
         ("@research" . ?r)
         (:startgroup)
         ("@buy" . ?B)
         ("@coding" . ?C)
         ("@errand" . ?E)
         ("@meeting" . ?M)
         ("@planning" . ?P)
         ("@writing" . ?W)
         (:endgroup)
         (:startgroup)
         ("@blocked" . ?b)
         ("@waiting" . ?w)
         (:endgroup)))
      ;; Record the date but not the time of day when a todo item is done
      (org-log-done 'time)
      (org-log-done-with-time nil)
      (org-log-into-drawer t)
      ;; By default, tasks have the lowest possible priority
      (org-priority-default org-priority-lowest)
      :config
      ;; When a recurring task is done, log the date but not the time
      (add-to-list 'org-log-note-headings '(state . "State %-12s from %-12S %d"))
      (defun nrm/org-done-fun ()
        "Interactively runs all the commands I should remember when finishing a task."
        (interactive)
        (call-interactively #'org-todo)
        (call-interactively #'org-set-tags-command)
        (call-interactively #'org-priority)))

  #+end_src

** Org agenda

#+begin_src emacs-lisp
  (use-package org-agenda
    :ensure org
    :custom
    ;; Display done items with their completion date
    (org-agenda-start-with-log-mode t)
    (org-agenda-log-mode-items '(closed clock state))
    (org-agenda-window-setup "current-window")
    ;; If an entry has a TODO label, don't check its children
    (org-agenda-todo-list-sublevels nil)
    (org-agenda-hide-tags-regexp "AgendaSource\\|Topic\\|Project\\|Person\\|Book\\|Company\\|Trip")
    :hook
    (org-agenda-mode . nrm/org-agenda-hook)
    (org-agenda-after-show . (lambda () (org-narrow-to-subtree)))
    :config
    (defun nrm/org-agenda-hook ()
      (display-line-numbers-mode -1)
      (hl-line-mode 1)))

  (use-package org-super-agenda
    :after org-agenda
    :config
    (org-super-agenda-mode 1)
    :custom
    (org-agenda-custom-commands
     '(("c" "Categories"
        ((alltodo ""
                  ((org-agenda-overriding-header "📁 Tasks by Project")
                   (org-super-agenda-groups
                    '((:auto-category t)))))))
       ("d" "Dashboard"
        ((alltodo ""
                  ((org-agenda-overriding-header "")
                   (org-super-agenda-groups
                    '((:discard ;; Filter out blocked, waiting, and scheduled tasks
                       (:tag ("@blocked" "@waiting") :scheduled t :deadline t))
                      (:name "🧙 In progress"
                             :todo "PROG")
                      (:name "✨ Current priorities"
                             :priority "A")
                      (:discard ;; Discard everything else
                       (:anything t))))))
         (agenda)))
       ("p" "Planning"
        ((agenda)
         (alltodo ""
                  ((org-agenda-overriding-header "")
                   (org-super-agenda-groups
                    '((:name "📥 Inbox: Untracked tasks"
                             :not (:tag ("@high" "@medium" "@low")))
                      (:name "⏳ Waiting"
                             :tag "@waiting"
                             :order 50)
                      (:name "🧱 Blocked"
                             :tag "@blocked"
                             :order 90)
                      (:name "📅 Scheduled"
                             :scheduled t
                             :deadline t
                             :order 51)
                      (:name "🧙 In progress"
                             :todo "PROG")
                      (:name "✨ Current priorities"
                             :priority "A")
                      (:name "🔜 Next up"
                             :priority "B")
                      (:name "📁 Backlog"
                             :anything t
                             :order 70))))))))))

#+end_src

** Roam

To make a header in a file into its own node, run ~org-id-get-create~.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Roam
  ;; _____________________________________________________________________________

  (use-package org-roam
    :demand
    :custom
    (org-roam-directory "~/roam")
    (org-roam-dailies-directory "daily")
    (org-roam-dailies-capture-templates
     '(("d" "default" entry "* %?" :target
        (file+head "%<%Y-%m-%d>.org"
                   "#+title: %<%Y-%m-%d>\n#+STARTUP: showeverything\n\n* Tasks [/]\n\n- [ ]"))))
    (org-roam-node-display-template
     (concat "${title:*} " (propertize "${tags:*}" 'face 'org-tag)))
    (org-roam-capture-templates
     (let ((default-file "roam-${slug}.org")
           (default-header "#+title: ${title}\n#+category: ${title}\n#+date: %U\n#+filetags: "))
       `(("t" "Topic" plain
          "%?"
          :target (file+head ,default-file ,(concat default-header ":Topic:"))
          :unnarrowed t)
         ("a" "Project" plain
          "* Goals\n%?\n* Actions\n"
          :target (file+head ,default-file ,(concat default-header ":Project:AgendaSource:"))
          :unnarrowed t)
         ("p" "Person" plain
          "%?"
          :target (file+head ,default-file ,(concat default-header ":Person:"))
          :unnarrowed t)
         ("b" "Book" plain
          "- Author: %?\n- Notes: \n\n* Summary\n\n* Chapters\n\n* Comments\n"
          :target (file+head ,default-file ,(concat default-header ":Book:"))
          :unnarrowed t)
         ("c" "Company" plain
          "- Website: %?\n- Tech stack: \n\n* Notes\n\n* Applications\n"
          :target (file+head ,default-file ,(concat default-header ":Company:"))
          :unnarrowed t)
         ("j" "Trip" plain
          "* Flights/travel\n\n* Accommodation\n\n* Comments\n"
          :target (file+head ,default-file ,(concat default-header ":Trip:AgendaSource:"))
          :unnarrowed t))))
    :bind (("s-r" . org-roam-node-find)
           :map org-mode-map
           ("M-s M-o" . consult-org-heading)
           ("C-c i" . org-roam-node-insert)
           ("C-c b" . org-roam-buffer-toggle)
           ("s-n" . org-roam-dailies-goto-next-note)
           ("s-p" . org-roam-dailies-goto-previous-note))
    :config
    (unless (file-exists-p org-roam-directory)
      (make-directory org-roam-directory))
    (org-roam-db-autosync-enable))
#+end_src

** File structure

- Define refiling targets as all Roam files.
- Generate default ~org-agenda-files~ based on the Roam files with a specific tag, ~AgendaSource~ by default.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Org file structure
  ;; _____________________________________________________________________________

  (defun nrm/generate-org-refile-targets ()
    (interactive)
    ;; Only this variable needs to be regenerated
    (setq roam-files (directory-files org-roam-directory t "org$"))
    (setq org-refile-targets
          '((roam-files :maxlevel . 3))))

  ;; Generate the refile target list when Emacs starts and also whenever a new Roam file is created (aprox)
  (nrm/generate-org-refile-targets)
  (add-hook 'org-capture-after-finalize-hook #'nrm/generate-org-refile-targets)

  ;; _____________________________________________________________________________
  ;; Org agenda
  ;; _____________________________________________________________________________

  (defun nrm/roam-list-files-with-tag (tag-name)
    (delete-dups (mapcar #'org-roam-node-file
                         (seq-filter
                          (lambda (elt) (member tag-name (org-roam-node-tags elt)))
                          (org-roam-node-list)))))

  (setq nrm/org-agenda-generating-tag "AgendaSource")

  (defun nrm/generate-org-agenda-files ()
    (interactive)
    (setq org-agenda-files (nrm/roam-list-files-with-tag nrm/org-agenda-generating-tag))
    (message "Agenda files now generated by the tag: %s" nrm/org-agenda-generating-tag))

  ;; Generate the agenda file list when Emacs starts and also whenever a new Roam file is created (aprox)
  (nrm/generate-org-agenda-files)
  (add-hook 'org-capture-after-finalize-hook #'nrm/generate-org-agenda-files)

  ;; _____________________________________________________________________________
  ;; Org capture
  ;; _____________________________________________________________________________

  (setq org-capture-templates
        '(("i" "Inbox" entry (file "~/roam/Inbox.org") "* TODO %?\n%U" :empty-lines 1)
          ("c" "Context" entry (file "~/roam/Inbox.org") "* TODO %?\n%U\n%a" :empty-lines 1)))
#+end_src

* Presenting

Olivetti is used to centre a buffer's contents in a window.

Logos does two things:
- makes it easier to navigate files according to a logical outline structure; and
- provides a "focus mode" that strips down a lot of the UI.

Combining the two is a simple way of presenting the contents of a buffer.

Olivetti doesn't play well with ~visual-fill-column-mode~, so I disable it automatically when I go into the focus mode. Technically I should disable it when going into ~olivetti~ instead, but I never use ~olivetti~ on its own, so I'm happy with this for now.

Doing a presentation messes up a bunch of the minor modes I use, so the simpler way to get out of it is to run the ~revert-buffer~ command.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Presenting
  ;; _____________________________________________________________________________

  (use-package olivetti
    :custom
    (olivetti-body-width 0.7)
    (olivetti-minimum-body width 80))

  (use-package logos
    :hook (logos-focus-mode . nrm/present-funs)
    :custom
    (logos-outlines-are-pages t)
    :config
    (setq-default logos-hide-cursor t
                  logos-hide-mode-line t
                  logos-hide-buffer-boundaries t
                  logos-hide-fringe t
                  logos-variable-pitch nil
                  logos-buffer-read-only t
                  logos-olivetti t)
    (defun nrm/present-funs ()
      (visual-fill-column-mode 0)
      (display-line-numbers-mode 0))
    :bind
    ("C-x n n" . logos-narrow-dwim)
    ("C-x ]" . logos-forward-page-dwim)
    ("C-x [" . logos-backward-page-dwim)
    (:map logos-focus-mode-map
          ("<right>" . logos-forward-page-dwim)
          ("<left>" . logos-backward-page-dwim)))
#+end_src

* RSS

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; RSS
  ;; _____________________________________________________________________________

  (use-package elfeed
    :custom
    (elfeed-feeds
     '(("https://xkcd.com/atom.xml" comix))))
#+end_src

* Shell

I use [[https://github.com/akermu/emacs-libvterm/][vterm]] because it is fast, supports interactive shell commands, and has served me well for many years.

The additional snippets of Elisp let me interactively create ~vterm~ buffers with arbitrary names and directories, at the root of projects, and quickly navigate to and between ~vterm~ buffers.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Shell
  ;; _____________________________________________________________________________

  (use-package vterm
    :demand t
    :hook (vterm-mode . goto-address-mode)
    :config
    (setq vterm-max-scrollback 10000))

  (defvar nrm/vterm-buffer-list nil
    "List of all managed vterm buffers.")

  (defun nrm/vterm-new-buffer (name dir)
    "Creates a new managed vterm buffer called NAME, with DIR default directory.
  Interactively, also switches to the new buffer."
    (interactive "MNew vterm buffer name:\nDDefault directory:")
    (let ((buffer (generate-new-buffer (generate-new-buffer-name (format "*vterm: %s*" name)))))
      (setq nrm/vterm-buffer-list (nconc nrm/vterm-buffer-list (list buffer)))
      (with-current-buffer buffer
        (cd dir)
        (vterm-mode)
        (add-hook 'kill-buffer-hook #'nrm/vterm-kill-buffer-hook nil t)
        (if (called-interactively-p 'any) (switch-to-buffer buffer))
        buffer)))

  (defun nrm/vterm-kill-buffer-hook ()
    "Removes vterm buffer from the list of managed buffers."
    (setq nrm/vterm-buffer-list (delq (current-buffer) nrm/vterm-buffer-list)))

  (defun nrm/vterm-next ()
    "Switches to the next managed vterm buffer, creating one if there are none."
    (interactive)
    (if (not nrm/vterm-buffer-list)
        (call-interactively #'nrm/vterm-new-buffer)
      (let ((buffer-list-len (length nrm/vterm-buffer-list))
            (my-index (cl-position (current-buffer) nrm/vterm-buffer-list)))
        (if my-index
            (switch-to-buffer (nth (mod (+ 1 my-index) buffer-list-len) nrm/vterm-buffer-list))
          (switch-to-buffer (car nrm/vterm-buffer-list))))))

  (defun nrm/vterm-project ()
    "If inside a project, creates a new managed vterm buffer at its root."
    (interactive)
    (if-let* ((name (project-name (project-current)))
              (dir (project-root (project-current))))
        (funcall-interactively #'nrm/vterm-new-buffer name dir)))


  (keymap-global-set "s-t" #'nrm/vterm-next)
  (keymap-global-set "s-T" #'nrm/vterm-new-buffer)
  (keymap-set project-prefix-map "t" #'nrm/vterm-project)
  (add-to-list 'project-switch-commands '(nrm/vterm-project "Vterm"))
#+end_src

* TRAMP

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; TRAMP
  ;; _____________________________________________________________________________

  (use-package tramp
    :custom
    (tramp-default-method "ssh")
    ;; Change this to get, for example, error messages only
    (tramp-verbose 3)
    ;; Load controlmaster options from ~/.ssh/config directly
    (tramp-use-ssh-controlmaster-options nil)
    :config
    (add-to-list 'tramp-connection-properties
                 (list "/ssh:" "direct-async-process" t)))
#+end_src

* Programming

** Rainbow delimiters

Makes delimiters, such as brackets and parentheses, stand out with depth-specific colours.

Did I have to manually select colours by linearly interpolating a rainbow? Absolutely not, and the defaults from this and other packages are probably more sensible from an accessibility perspective. Did I do it anyway? Heck yeah, and now I'm so attached to these colours I don't want to switch to anything else.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Rainbow delimiters
  ;; _____________________________________________________________________________

  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode)
    :config
    (set-face-background 'rainbow-delimiters-base-error-face "#e6194b")
    (set-face-foreground 'rainbow-delimiters-depth-1-face "#e6194b")
    (set-face-foreground 'rainbow-delimiters-depth-2-face "#f58231")
    (set-face-foreground 'rainbow-delimiters-depth-3-face "#ffe119")
    (set-face-foreground 'rainbow-delimiters-depth-4-face "#bfef45")
    (set-face-foreground 'rainbow-delimiters-depth-5-face "#aaffc3")
    (set-face-foreground 'rainbow-delimiters-depth-6-face "#42d4f4")
    (set-face-foreground 'rainbow-delimiters-depth-7-face "#4363d8")
    (set-face-foreground 'rainbow-delimiters-depth-8-face "#911eb4")
    (set-face-foreground 'rainbow-delimiters-depth-9-face "#f032e6"))
#+end_src

** Compilation

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Compilation
  ;; _____________________________________________________________________________

  (use-package compile
    :ensure nil
    :hook
    (compilation-mode . goto-address-mode)
    (compilation-mode . nrm/meta-buffer-mode)
    :custom
    (compilation-scroll-output t))

#+end_src


For specific projects/languages, use directory-local variables to set sensible default compilation commands. For example, for Rust:

#+begin_src emacs-lisp :tangle no :eval never
((nil . ((compile-command . "echo Formatting... && cargo fmt && echo Linting... && cargo clippy --benches --tests --all-features --all-targets -- -D warnings && echo Testing... && cargo test "))))
#+end_src

** Flymake

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Flymake
  ;; _____________________________________________________________________________

  (use-package flymake
    :bind
    (:map flymake-mode-map
          ("M-n" . flymake-goto-next-error)
          ("M-p" . flymake-goto-prev-error)))
#+end_src

** Eglot

Enable LSP support for the languages I use most often.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Eglot
  ;; _____________________________________________________________________________

  (use-package eglot
    :init
    (dolist (hook
             '(go-ts-mode-hook
               java-ts-mode-hook
               kotlin-ts-mode-hook
               python-ts-mode-hook
               rust-ts-mode-hook
               typescript-ts-mode-hook))
      (add-hook hook 'eglot-ensure))
    :bind
    (:map eglot-mode-map
          ("s-e" . eglot-code-actions))
    :custom
    (eglot-events-buffer-size 0)
    (eglot-autoshutdown t)
    ;; Don't block when waiting for LSP connections
    (eglot-sync-connect nil)
    ;; Don't clutter display with code actions
    (eglot-code-action-indications nil)
    (eglot-ignored-server-capabilities '(:documentHighlightProvider))
    :config
    (add-to-list 'eglot-stay-out-of 'imenu))

#+end_src

** Tree-Sitter

Configure tree-sitter to automatically use available ts-modes by default. Tree-sitter will automatically ask whether to install a language grammar when first visiting a file of a language with a known ts-mode.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Tree-Sitter
  ;; _____________________________________________________________________________

  (use-package treesit
    :ensure nil
    :custom
    (treesit-enabled-modes t)
    (treesit-font-lock-level 4))

#+end_src

* File formats

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; File formats
  ;; _____________________________________________________________________________
#+end_src

** CSV

Toggle ~csv-align-mode~ to display columns aligned, without changing the underlying file.

#+begin_src emacs-lisp
  (use-package csv-mode
    :mode ("\\.csv\\'" . csv-mode)
    :custom (csv-invisibility-default nil))
#+end_src

* Beancount

Follow the instructions in my beans repo to install all the needed Python packages.

#+begin_src emacs-lisp
  ;; ___________________________________________________________________________
  ;; Beancount
  ;; ___________________________________________________________________________

  (use-package beancount
    :mode ("\\.beancount\\'" . beancount-mode)
    :init
    (add-hook 'beancount-mode-hook #'outline-minor-mode)
    :bind
    (:map beancount-mode-map
          ("C-c C-n" . outline-next-visible-heading)
          ("C-c C-p" . outline-previous-visible-heading)))
#+end_src

* Buffer display rules

** Meta buffers

I often work with buffers that hold links to many other buffers. For example:
- An ~org-agenda~ buffer, which holds links to tasks in ~org~ buffers
- A ~dired~ buffer, which holds links to file buffers
- A ~compilation~ buffer, which holds compilation diagnostics and links to positions in source files


When working with these "meta" buffers, I want to keep them always open, so I can have an overview of the context, and also open the buffers they link to in a consistent way. This usually means having a frame with two side-by-side windows, displaying the meta buffer on the left window and using the right window to display all other buffers.

By defining a minor mode and creating a buffer display rule for it, I can enable this behaviour consistently across different major modes.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Meta buffer mode
  ;; _____________________________________________________________________________

  (define-minor-mode nrm/meta-buffer-mode
    "Override buffer display rules to display most other buffers in window to the right.")

  (defun nrm/from-meta-buffer-p (_buffer-or-name _action)
    "Returns non-nil iff nrm/meta-buffer-mode is enabled in the current buffer.
  This function is meant to be used as a condition in display-buffer-alist."
    nrm/meta-buffer-mode)

  (defun nrm/display-buffer-reuse-window-direction (buffer alist)
    "Reuse the window in a given direction relative to the selected window, if possible."
    (when-let* ((direction (cdr (assq 'direction alist)))
                (win (window-in-direction direction)))
      (window--display-buffer buffer win 'reuse alist)))
#+end_src


I want this minor mode to be enabled in ~org-agenda~ buffers iff ~org-agenda-follow-mode~ is enabled. Note that ~org-agenda-follow-mode~ is a function and not a real mode, so I have to add an advice to the function instead of to a hook.

Additionally, refreshing an ~org-agenda~ buffer (~org-agenda-redo~ or ~org-agenda-redo-all~) resets many of the minor modes, so I need to re-enable ~nrm/meta-buffer-mode~ after refreshing the agenda.

#+begin_src emacs-lisp

  (advice-add 'org-agenda-follow-mode :after (lambda () (nrm/meta-buffer-mode 'toggle)))

  (add-hook 'org-agenda-finalize-hook
            (lambda () (if org-agenda-follow-mode
                           (nrm/meta-buffer-mode)
                         (nrm/meta-buffer-mode -1))))
#+end_src

** Rules

Rules on where and how to display certain buffers.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Buffer display rules
  ;; _____________________________________________________________________________

  (defun nrm/get-named-frame (name)
    "Returns a frame with the given NAME, creating it if necessary"
    (or (cdr (assoc-string name (make-frame-names-alist)))
        (make-frame `((name . ,name)))))

  (defun nrm/display-buffer-in-named-frame (buffer alist)
    "Displays BUFFER in a frame with a given name, creating it if necessary.
    ALIST should contain a symbol 'frame-name', whose value is either:
    - The string name of the target frame;
    - A function that accepts BUFFER and ALIST and returns the name of the target frame."
    (let ((frame-name (cdr (assq 'frame-name alist))))
      (when (functionp frame-name)
        (setq frame-name (funcall frame-name buffer alist)))
      (select-frame (nrm/get-named-frame frame-name))
      (display-buffer-full-frame buffer alist)))

  (setq display-buffer-alist
        '(
          ;; Display temporary buffers below the current window
          ((or . ((derived-mode . calendar-mode)
                  "\\*Embark Actions\\*"
                  "\\*transient\\*"))
           (display-buffer-reuse-window display-buffer-below-selected)
           (window-height . fit-window-to-buffer)
           (window-parameters . ((no-other-window . t)
                                 (mode-line-format . none))))

          ;; Display compilation buffers in a dedicated frame
          ("\\*compilation\\*"
           nrm/display-buffer-in-named-frame
           (frame-name . "Compilation"))

          ;; Display temporary org source buffers in the same window
          ("\\*Org Src .*\\*"
           display-buffer-same-window)

          ;; When in a meta buffer, open most other buffers in a window to the right
          (nrm/from-meta-buffer-p
           (nrm/display-buffer-reuse-window-direction display-buffer-in-direction)
           (window-width . 0.5)
           (direction . right))

          ;; Display magit status buffers in a dedicated window per repository
          ((derived-mode . magit-status-mode)
           nrm/display-buffer-in-named-frame
           (frame-name . (lambda (buffer _alist) (buffer-name buffer))))

          ;; Make some magit mode buffers take up the full frame
          ((or . ((derived-mode . magit-log-mode)
                  (derived-mode . magit-stash-mode)
                  (derived-mode . magit-revision-mode)))
           display-buffer-full-frame)

          ))
#+end_src


Elfeed does not respect the rule of using ~display-buffer~ to display its buffers, so I can't use ~display-buffer-alist~ to configure it. Instead, I add an advice to always switch to an elfeed-dedicated frame before running the ~elfeed~ command.

#+begin_src emacs-lisp
  (defun nrm/switch-to-elfeed-frame ()
    (select-frame-set-input-focus (nrm/get-named-frame "elfeed")))

  (advice-add 'elfeed :before #'nrm/switch-to-elfeed-frame)

#+end_src

* Shortcuts transient

There are some actions I perform often, such as navigating to certain files/directories, or running certain commands. Here I put them all in a transient command, so I can easily access them, and be reminded of the shortcuts when I forget.

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Shortcuts transient
  ;; _____________________________________________________________________________

  (defun nrm/org-roam-dailies-goto-latest ()
    "Navigate to the latest existing Org-roam daily note."
    (interactive)
    (if-let* ((daily-files (org-roam-dailies--list-files))
              (latest-file (car (sort daily-files #'string>))))
        (find-file latest-file)
      (message "No daily notes found.")))

  (defun nrm/goto-planning-view ()
    "Go to the planning view, or create it if necessary."
    (interactive)
    (let* ((frame-name "Task planning")
           (frame (cdr (assoc-string frame-name (make-frame-names-alist)))))
      (if frame
          (select-frame-set-input-focus frame)
        (progn
          (select-frame-set-input-focus (nrm/get-named-frame frame-name))
          (redisplay) ;; must happen before resizing
          (set-frame-size-and-position (selected-frame) (/ 2.0 3) 1.0 (/ 1.0 6) 0.0)
          (split-window-right)
          (org-agenda nil "p")
          (org-agenda-follow-mode)))))

  (transient-define-prefix nrm/shortcuts-transient nil
    "Commands for my commonly used actions/navigation."
    ["Shortcuts"
     ["Daily notes"
      ("d" "Date's daily" (lambda () (interactive) (org-roam-dailies-goto-date nil "d")))
      ("t" "Today's daily" (lambda () (interactive) (org-roam-dailies-goto-today "d")))
      ("T" "Latest daily" nrm/org-roam-dailies-goto-latest)]
     ["Emacs config"
      ("e" "Emacs config file" (lambda () (interactive) (find-file "~/.emacs.d/README.org")))
      ("l" "Local config file" (lambda () (interactive) (find-file nrm/local-config-file)))]
     ["Misc"
      ("f" "Elfeed" elfeed)
      ("g" "Git repo dashboard" magit-list-repositories)
      ("p" "Task planning" nrm/goto-planning-view)
      ("r" "Roam directory" (lambda () (interactive) (find-file org-roam-directory)))
      ("s" "SUDO home" (lambda () (interactive) (find-file "/sudo::/")))
      ]
     ])

  (global-set-key (kbd "s-g") #'nrm/shortcuts-transient)

#+end_src

* End

#+begin_src emacs-lisp
  ;; _____________________________________________________________________________
  ;; Finish loading config
  ;; _____________________________________________________________________________

  (toggle-debug-on-error)

  (message "Finished loading config at %s" (format-time-string "%T"))
  (message "Emacs loaded in %s with %d garbage collections.\n"
           (format "%.2f seconds"
                   (float-time
                    (time-subtract after-init-time before-init-time)))
           gcs-done)
#+end_src
